name: Release

on:
  push:
    tags:
      - 'v*'

  pull_request:
    branches: ["main"]

permissions:
  # for create release tag
  contents: write

jobs:
  test:
    runs-on: windows-2019

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      # - name: Install NuGet
      #   run: Install-PackageProvider -Name NuGet -Force -Scope CurrentUser

      - name: Get Tag Version
        id: tag_version
        # run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
        # run:  echo "tag=${GITHUB_REF#refs/*/}"
        run:  |
          $tag = $env:GITHUB_REF -replace 'refs/tags/', ''
          echo $tag
          echo "tag=${tag}" >> $GITHUB_OUTPUT
      - name: Generate PSD1
        run: |
          $tagVersion = ${{ steps.tag_version.outputs.tag }}
          echo $tagVersion
          $tagVersion = $tagVersion -replace '^v', ''  # 先頭の 'v' を削除
          $content = Get-Content Kernel32Dll/Kernel32Dll.psd1 -Raw
          # replace 
          $content  -replace '#tagVersion', "$tagVersion" |
            Set-Content -Path Kernel32Dll/Kernel32Dll.psd1
        
      - name: Publish Module
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: Publish-Module -Path ./Kernel32Dll -NuGetApiKey  "$env:NUGET_API_KEY"

      - name: Release tag
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
